### ISSUE TITLE
Bug Report: Linux version of DDTO+ not loading

### ISSUE THREAD

**Issue by Sonicgamer2000** [Jorge-SunSpirit/Doki-Doki-Takeover#29]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Doki Doki Takeover) before submitting an issue.
So I'm trying to play the Linux release of Doki Doki Takeover Plus when this error kept occuring. 
![Screenshot 2023-03-17 10 47 26 PM](https://user-images.githubusercontent.com/92794798/226080374-b93467f9-8e7b-42c6-94db-fb812b56e2e2.png)
I'm currently trying to figure out the problem in question but to no avail.
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
Linux
## What version of the game are you using? Look in the bottom left corner of the main menu.
3.0.3
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
All I did was make the file executible & the error occured
## Please describe your issue. Provide extensive detail and images if possible.
Didn't I already say the issue above?

**Comment by ActualMandM** [comment]
I believe in this case you either have to update your Linux distro or compile it yourself.

Thankfully we just added Haxe Module Manager support so compiling it manually shouldn't have too much issue.

**Comment by Nexenek** [comment]
Had the same issue with osu lazer new version today compiling it helped but you probably should consider upgrading your distro.

For easier method you can try downloading win version and run it with lutris (worked for me)

**Comment by MagelessMayhem** [comment]
Yeah, it seems like you're using Chrome OS's Crostini shell.

At the time of writing, Crostini runs off a custom Debian 11 container (although it will soon upgrade to Debian 12). Debian 11 uses Glibc 2.31, a version too old for DDT to run off. You _should_ be able to change the repository in `/etc/apt/sources.list` from `bullseye` to `bookworm` and then issuing a system upgrade via `sudo apt update && sudo apt dist-upgrade`.

Debian 12, the next version of Debian due to come out in May, uses Glibc 2.36, which is sufficient for both compiling and running the game. See if this fixes your problem.

**Comment by ActualMandM** [comment]
Wait, does the older libc version also prevent you from compiling it?

**Comment by MagelessMayhem** [comment]
Well, they could attempt to compile it themselves, since my guess is the Linux binary was compiled on an Ubuntu machine (22.04, perhaps?). A hard dependency on Glibc >= 2.33 during compilation would prevent this, though.

I haven't tested this on any version of Glibc lower than 2.34, so I can't judge for myself.

**Comment by Sonicgamer2000** [comment]
So I upgraded my distro but now there's no sound AT ALL. I tried going to other stuff to see if there was any sound but there isn't sound playing. Not. One. Sound.

**Comment by Sonicgamer2000** [comment]
So I  forgot how I updated my distro apparently.

**Comment by Sonicgamer2000** [comment]
Nevermind. I just had to redo the whole process and now it works
